### PR TITLE
Fixed error message output damaging AJAX results on file upload, resolves #25

### LINKED ISSUE #25: dont show sql errors in ajax requests
feature/fix?
better error handling for ajax requests which dont breaks json answers.
SQL erors should only be shown to admins.

### PR DESCRIPTION
**Pull request by milux**
This patch changes the error output. It uses a custom HTTP header "X-CT-Error" instead of outputting the error message with the body, possibly damaging JSON results (as for instance after file uploads).
To avoid errors thrown by the header() function, output buffering has been enabled, so that all data will definitely be flushed after the header() calls.
For performance, output buffering has been registered with the "ob_gzhandler" which does automatic gzip compression of the response body for supporting browsers.

### CODE REVIEW

**Comment by milux** [comment]
This patch likely resolves bug #25.

File: system/includes/start.php [hunk 1]
```diff
@@ -37,11 +39,10 @@
...
  */
 function handleShutdown() {
-  global $ajax;
   $error = error_get_last();
-  if (!$ajax && $error !== NULL) { // no Error notizes on ajax requests!
-    $info = "[ERROR] file:" . $error['file'] . ":" . $error['line'] . " <br/><i>" . $error['message'] . '</i>' . PHP_EOL;
-    echo '<div class="alert alert-error">' . $info . '</div>';
+  if (isset($error) && $error['type'] !== E_DEPRECATED) {
+    $info = $error['file'] . ' (line ' . $error['line'] . '): ' . $error['message'];
+	header('X-CT-Error: ' . $info);
```
Comment (isbm) [inline system/includes/start.php]: @milux, thanks for the patch!
A little nitpick here: please make indent better as well as you don't need to create `$info` var, but just put all that stuff into the header right away.

**Comment by milux** [comment]
Sorry, one was a tab stop and the other was 4 spaces, in my editor they looked identical.
GitHub on the other hand resolves a tab stop with 2 spaces... ^^
You are right with this variable, but as you can see, I just followed the previous coding style of that function. Thought someone regarded this to be more clear to read or something the like. ;)

**Comment by isbm** [comment]
@milux Thanks! Well, you don't always need to do exactly like others. :wink:
